import { Inter, Roboto_Slab } from "next/font/google";
import "./globals.css";
import PageConnectKit from "@/context/PageConnectKit";
import WalletContextProvider from "@/context/WalletContextProvider";
import Navbar from "@/components/landingComponents/navbar";
import { Footer } from "@/components";

const roboto_Slab = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto_Slab.className}>
        {/* <WalletContextProvider> */}
        <PageConnectKit>
          {/* <Navbar /> */}
          {children}
          {/* <Footer /> */}
        </PageConnectKit>
        {/* </WalletContextProvider> */}
      </body>
    </html>
  );
}
